### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Nuku** [cswendrowski/FoundryVTT-Encounter-Builder#15]
![image](https://user-images.githubusercontent.com/886729/153938123-ef860688-e464-4c69-aeb7-495ba80e119c.png)
I get the above, I try to fill things in.
![image](https://user-images.githubusercontent.com/886729/153938241-47d69f7d-b061-421d-b85b-e7d1f6b4e6d8.png)
But I see nothing to click, and nothing to do. What is the next step?!
I tried filling the others.
![image](https://user-images.githubusercontent.com/886729/153938359-277669f1-ee86-4a5d-8cc5-f42bd89b1885.png)

**Comment by ronniegrahn** [comment]
I sometimes get this when trying to change the size. Closing and refreshing (F5) seems to work for me.

**Comment by Nuku** [comment]
This did not work for me.

**Comment by Nuku** [comment]
Waiting was the key, also lowering how many compendiums it searches to begin with.
